services:

  frontend_service_user:
    container_name: fe_service_user
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    volumes:
      - ./app:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5001:8080"
    environment:
      TZ: Europe/Berlin

