services:

  frontend_service_user:
    container_name: fe_service_user
    build:
      context: ./Frontend
      dockerfile: ./Frontend/Dockerfile.dev
    volumes:
      - ./Frontend:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5001:8080"
    environment:
      TZ: Europe/Berlin

  backend_service_user:
    container_name: be_service_user
    build:
      context: ./Backend
      dockerfile: ./Backend/Dockerfile.dev
    volumes:
      - ./Backend/index.js:/app/index.js
      - ./Backend/service/api:/app/service/api
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4001:3000"
    environment:
      TZ: Europe/Berlin

  mongo-user:
    container_name: db_user
    image: mongo:latest
    volumes:
      - ./mongodb_user:/data/db
    ports:
      - "35555:27017"
    command: mongod --quiet --logpath /dev/null
